apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  source:
    repoURL: https://github.com/JorgeP7/test-external-secret.git
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true